from __future__ import annotations

import argparse
import csv
import json
import math
import re
from pathlib import Path
from typing import Any

import torch


def _extract_epoch_from_name(path: Path) -> int:
    m = re.search(r"epoch_(\d+)", path.stem)
    if not m:
        raise ValueError(f"Cannot parse epoch number from filename: {path.name}")
    return int(m.group(1))


def _load_tensor(payload: dict[str, Any], *keys: str, required: bool = True) -> torch.Tensor | None:
    for key in keys:
        if key in payload and torch.is_tensor(payload[key]):
            return payload[key].float()
    if required:
        raise KeyError(f"Missing tensor field. Tried keys={keys}")
    return None


def _normalize(x: torch.Tensor) -> torch.Tensor:
    return x / x.norm(dim=-1, keepdim=True).clamp_min(1e-6)


def _write_csv(rows: list[dict[str, Any]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fieldnames = list(rows[0].keys())
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _safe_mean(vals: list[float]) -> float:
    if not vals:
        return float("nan")
    return float(sum(vals) / len(vals))


def _safe_std(vals: list[float]) -> float:
    if not vals:
        return float("nan")
    mu = sum(vals) / len(vals)
    var = sum((x - mu) ** 2 for x in vals) / len(vals)
    return float(math.sqrt(var))


def _safe_corr(x: list[float], y: list[float]) -> float:
    if len(x) < 2 or len(y) < 2 or len(x) != len(y):
        return float("nan")
    mx = sum(x) / len(x)
    my = sum(y) / len(y)
    vx = sum((v - mx) ** 2 for v in x)
    vy = sum((v - my) ** 2 for v in y)
    if vx <= 1e-12 or vy <= 1e-12:
        return float("nan")
    cov = sum((a - mx) * (b - my) for a, b in zip(x, y))
    return float(cov / math.sqrt(vx * vy))


@torch.no_grad()
def analyze_prototype_history(
    run_dir: Path,
    output_dir: Path | None = None,
    file_glob: str = "epoch_*.pt",
    allow_mu_only: bool = False,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]]:
    proto_dir = run_dir / "prototype_history"
    if not proto_dir.exists():
        raise FileNotFoundError(f"prototype_history not found: {proto_dir}")

    ckpt_paths = sorted(proto_dir.glob(file_glob), key=_extract_epoch_from_name)
    if not ckpt_paths:
        raise FileNotFoundError(f"No files matched: {proto_dir / file_glob}")

    class_rows: list[dict[str, Any]] = []
    epoch_rows: list[dict[str, Any]] = []

    mu0_by_class: dict[int, torch.Tensor] = {}
    mu_prev_by_class: dict[int, torch.Tensor] = {}

    has_alpha_trace = True

    for ckpt_path in ckpt_paths:
        payload = torch.load(ckpt_path, map_location="cpu")
        epoch = int(payload.get("epoch", _extract_epoch_from_name(ckpt_path)))

        class_ids = [int(x) for x in payload["class_ids"]]
        class_names = [str(x) for x in payload["class_names"]]
        mu = _load_tensor(payload, "mu", "prototypes", required=True)
        alpha = _load_tensor(payload, "alpha", required=False)
        trace_sigma = _load_tensor(payload, "trace_sigma", required=False)

        if alpha is None or trace_sigma is None:
            has_alpha_trace = False
            if not allow_mu_only:
                raise RuntimeError(
                    f"{ckpt_path.name} does not contain alpha/trace_sigma. "
                    "Use a run generated by the updated training code, or pass --allow-mu-only."
                )

        mu_normed = _normalize(mu)

        trace_vals: list[float] = []
        alpha_vals: list[float] = []
        mu_norm_vals: list[float] = []
        cos_init_vals: list[float] = []
        cos_prev_vals: list[float] = []
        l2_init_vals: list[float] = []
        l2_prev_vals: list[float] = []

        for i, class_id in enumerate(class_ids):
            class_name = class_names[i]
            mu_i = mu[i]
            mu_i_normed = mu_normed[i]

            if class_id not in mu0_by_class:
                mu0_by_class[class_id] = mu_i.clone()
            if class_id not in mu_prev_by_class:
                mu_prev_by_class[class_id] = mu_i.clone()

            mu0 = mu0_by_class[class_id]
            mu_prev = mu_prev_by_class[class_id]
            mu0_normed = _normalize(mu0.unsqueeze(0))[0]
            mu_prev_normed = _normalize(mu_prev.unsqueeze(0))[0]

            cos_mu_to_init = float((mu_i_normed * mu0_normed).sum().item())
            cos_mu_to_prev = float((mu_i_normed * mu_prev_normed).sum().item())
            l2_mu_to_init = float((mu_i - mu0).norm().item())
            l2_mu_to_prev = float((mu_i - mu_prev).norm().item())
            mu_norm = float(mu_i.norm().item())

            row = {
                "epoch": epoch,
                "class_id": class_id,
                "class_name": class_name,
                "mu_norm": mu_norm,
                "cos_mu_to_init": cos_mu_to_init,
                "cos_mu_to_prev": cos_mu_to_prev,
                "l2_mu_to_init": l2_mu_to_init,
                "l2_mu_to_prev": l2_mu_to_prev,
            }

            if alpha is not None:
                row["alpha"] = float(alpha[i].item())
                alpha_vals.append(row["alpha"])
            if trace_sigma is not None:
                row["trace_sigma"] = float(trace_sigma[i].item())
                trace_vals.append(row["trace_sigma"])

            mu_norm_vals.append(mu_norm)
            cos_init_vals.append(cos_mu_to_init)
            cos_prev_vals.append(cos_mu_to_prev)
            l2_init_vals.append(l2_mu_to_init)
            l2_prev_vals.append(l2_mu_to_prev)

            class_rows.append(row)
            mu_prev_by_class[class_id] = mu_i.clone()

        epoch_row = {
            "epoch": epoch,
            "num_tracked_classes": len(class_ids),
            "mean_mu_norm": _safe_mean(mu_norm_vals),
            "std_mu_norm": _safe_std(mu_norm_vals),
            "mean_cos_mu_to_init": _safe_mean(cos_init_vals),
            "mean_cos_mu_to_prev": _safe_mean(cos_prev_vals),
            "mean_l2_mu_to_init": _safe_mean(l2_init_vals),
            "mean_l2_mu_to_prev": _safe_mean(l2_prev_vals),
        }

        if alpha_vals:
            epoch_row["mean_alpha"] = _safe_mean(alpha_vals)
            epoch_row["std_alpha"] = _safe_std(alpha_vals)
        if trace_vals:
            epoch_row["mean_trace_sigma"] = _safe_mean(trace_vals)
            epoch_row["std_trace_sigma"] = _safe_std(trace_vals)
        if alpha_vals and trace_vals:
            epoch_row["corr_alpha_vs_trace_sigma"] = _safe_corr(alpha_vals, trace_vals)

        epoch_rows.append(epoch_row)

    summary = {
        "run_dir": str(run_dir),
        "prototype_history_dir": str(proto_dir),
        "num_epoch_files": len(ckpt_paths),
        "first_epoch": int(epoch_rows[0]["epoch"]),
        "last_epoch": int(epoch_rows[-1]["epoch"]),
        "tracked_class_ids": sorted({int(r["class_id"]) for r in class_rows}),
        "has_alpha_trace": bool(has_alpha_trace),
        "outputs": {},
    }

    if output_dir is None:
        output_dir = run_dir / "variance_analysis"
    output_dir.mkdir(parents=True, exist_ok=True)

    class_csv = output_dir / "prototype_class_trajectory.csv"
    epoch_csv = output_dir / "prototype_epoch_summary.csv"
    summary_json = output_dir / "prototype_analysis_summary.json"

    _write_csv(class_rows, class_csv)
    _write_csv(epoch_rows, epoch_csv)
    summary["outputs"] = {
        "class_csv": str(class_csv),
        "epoch_csv": str(epoch_csv),
        "summary_json": str(summary_json),
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    return class_rows, epoch_rows, summary


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Analyze text_only_bayes_coop prototype_history saved during training. "
            "Prefers per-epoch files containing mu/alpha/trace_sigma; can optionally fall back to mu-only analysis."
        )
    )
    parser.add_argument("--run-dir", type=str, required=True, help="Path to one run_dir")
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Optional output directory. Defaults to <run_dir>/variance_analysis",
    )
    parser.add_argument(
        "--glob",
        type=str,
        default="epoch_*.pt",
        help="Glob pattern under prototype_history/, default: epoch_*.pt",
    )
    parser.add_argument(
        "--allow-mu-only",
        action="store_true",
        help="Allow analysis when alpha/trace_sigma are missing. In that case only mu trajectory metrics are produced.",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    run_dir = Path(args.run_dir).resolve()
    output_dir = Path(args.output_dir).resolve() if args.output_dir is not None else None

    _, _, summary = analyze_prototype_history(
        run_dir=run_dir,
        output_dir=output_dir,
        file_glob=args.glob,
        allow_mu_only=bool(args.allow_mu_only),
    )

    print("Analysis completed.")
    print(f"  class trajectory csv: {summary['outputs']['class_csv']}")
    print(f"  epoch summary csv:    {summary['outputs']['epoch_csv']}")
    print(f"  summary json:         {summary['outputs']['summary_json']}")
    print("\nRecommended columns to inspect:")
    print("  prototype_class_trajectory.csv:")
    print("    - alpha")
    print("    - trace_sigma")
    print("    - mu_norm")
    print("    - cos_mu_to_init")
    print("    - cos_mu_to_prev")
    print("    - l2_mu_to_init")
    print("    - l2_mu_to_prev")
    print("  prototype_epoch_summary.csv:")
    print("    - mean_alpha")
    print("    - mean_trace_sigma")
    print("    - mean_cos_mu_to_init")
    print("    - mean_cos_mu_to_prev")
    print("    - mean_l2_mu_to_init")
    print("    - mean_l2_mu_to_prev")


if __name__ == "__main__":
    main()
